//
//  YYUIShapedView.h
//  YYUIKit
//
//  Created by liuxc on 2021/11/16.
//

#import <UIKit/UIKit.h>

@protocol YYUIShapeGenerating;

/**
 YYUIShapedView is a primitive view class which makes it easy to style the shape
 of the view's edges and corners.

 YYUIShapedView manages mapping the paths generated by the shapeGenerator to the
 backing CAShapeLayer whenever the view is resized.
 */
@interface YYUIShapedView : UIView

/**
 The elevation of the layer in points.

 The higher the elevation, the more spread out the shadow is. This is distinct from the layer's
 zPosition which can be used to order overlapping layers, but will have no affect on the size of
 the shadow.

 Negative values act as if zero were specified.
 */
@property(nonatomic, assign) CGFloat elevation;

/**
 The shape generator used to generate a new CGPath whenever the view is resized.
 */
@property(nonatomic, strong, nullable) IBOutlet id<YYUIShapeGenerating> shapeGenerator;

/**
 The stroke color of the shape generated by shapeGenerator.

 The default is nil, which results in no stroke being drawn.
 */
@property(nonatomic, copy, nullable) UIColor *shapedBorderColor;

/**
 The stroke width of the shape generated by shapeGenerator.

 The default is 0, which results in no stroke being drawn.
 */
@property(nonatomic, assign) CGFloat shapedBorderWidth;

/**
 Initializes an YYUIShapedView.

 @param frame The frame of the shaped view.
 @param shapeGenerator The shape generator used to set the shape of the view.
 */
- (nonnull instancetype)initWithFrame:(CGRect)frame
                       shapeGenerator:(nullable id<YYUIShapeGenerating>)shapeGenerator
    NS_DESIGNATED_INITIALIZER;

@end

