workspace 'YYUICatalog.xcworkspace'
project 'YYUICatalog.xcodeproj'

target 'YYUICatalog' do
  use_frameworks!
  platform :ios, '10.0'
  project 'YYUICatalog.xcodeproj'

  pod 'YYUIKit', :path => '../'
  pod 'CatalogByConvention', "~> 2.5"
  
  pod 'SnapKit'
  pod 'Masonry'
  pod 'PinLayout'
  
  pod 'DDComponent', :git => 'https://github.com/liuxc123/DDComponent.git', :tag => '1.0.3'
  pod 'IBPCollectionViewCompositionalLayout'
  
  # Debug
  pod 'LookinServer', :configurations => ['Debug']
end
