workspace 'YYUICatalog.xcworkspace'
project 'YYUICatalog.xcodeproj'

target 'YYUICatalog' do
  platform :ios, '10.0'
  project 'YYUICatalog.xcodeproj'

  pod 'YYUIKit', :path => '../'
  pod 'CatalogByConvention', "~> 2.5"
  
  pod 'SnapKit'
  pod 'Masonry'
  
  # Debug
  pod 'LookinServer', :configurations => ['Debug']
  
  use_frameworks!
end
